export interface MembershipTier {
  id: string; // Will be a UUID generated by Supabase
  name: string; // e.g., "Gold", "Silver", "Platinum"
  price: number; // Cost of the tier
  duration_months: number; // Duration in months
  benefits: string[]; // List of benefits, e.g., ["Free haircut", "10% off products"]
  description?: string; // Optional detailed description
  // created_at and updated_at will be managed by Supabase
} 